name: weathercloset
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_core: ^3.10.1
  google_fonts: ^6.2.1
  firebase_auth: ^5.4.1
  shared_preferences: ^2.3.5
  cloud_firestore: ^5.6.2
  firebase_storage: ^12.4.1
  image_picker: ^1.1.2
  provider: ^6.1.2
  permission_handler: ^11.3.1
  go_router: ^14.7.2
  flutter_gemini: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
