name: classify
description: "A new Flutter project."
publish_to: 'none'
version: 0.2.1+4

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_core: ^3.10.1
  google_fonts: ^6.2.1
  firebase_auth: ^5.4.1
  shared_preferences: ^2.3.5
  cloud_firestore: ^5.6.2
  firebase_storage: ^12.4.1
  image_picker: ^1.1.2
  provider: ^6.1.2
  permission_handler: ^11.3.1
  go_router: ^14.7.2
  google_generative_ai: ^0.4.6
  geolocator: ^13.0.2
  http: ^1.3.0
  hive: ^2.2.3
  hive_generator: ^2.0.1
  path_provider: ^2.1.5
  uuid: ^4.5.1
  rxdart: ^0.28.0
  dio: ^5.8.0+1
  dart_jsonwebtoken: ^2.17.0
  intl: ^0.19.0
  cloud_functions: ^5.4.0
  google_sign_in: ^6.3.0
  package_rename: ^1.10.0
  webview_flutter: ^4.11.0
  connectivity_plus: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.14

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/woman_model.jpg
    - assets/icons8-구글-로고-144.png
    - assets/bad_logo_icon.png
    - assets/logo_icon_with_text.png
    - assets/logo_icon.png      
    - assets/11.png   
    - assets/22.png      
    - assets/splash_image.png     

  fonts:
    - family: Paperlogy
      fonts:
        - asset: assets/fonts/Paperlogy-1Thin.ttf
          weight: 100
        - asset: assets/fonts/Paperlogy-2ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Paperlogy-3Light.ttf
          weight: 300
        - asset: assets/fonts/Paperlogy-4Regular.ttf
          weight: 400
        - asset: assets/fonts/Paperlogy-5Medium.ttf
          weight: 500
        - asset: assets/fonts/Paperlogy-6SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Paperlogy-7Bold.ttf
          weight: 700
        - asset: assets/fonts/Paperlogy-8ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Paperlogy-9Black.ttf
          weight: 900

package_rename_config:
  android:
    app_name: Classify
    package_name: com.seongjko.classify
    override_old_package: com.example.weathercloset
    lang: kotlin